## Naive Bayes - Mushroom Dataset

- Goal : Predict the class of mushrooms , given some fetaures about the mushroom.
- Use naive bayes model for classification.

## Load The DataSet

In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("/Volumes/part3/MushroomDataSet/mushrooms.csv")
df.head(n=10)

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   
5    e         x           y         y       t    a               f   
6    e         b           s         w       t    a               f   
7    e         b           y         w       t    l               f   
8    p         x           y         w       t    p               f   
9    e         b           s         y       t    a               f   

  gill_spacing gill_size gill_color   ...   stalk_surface_below_ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   
5            c         b          n   ...                          s   
6            c         b          g   ...                          s   
7            c         b          n   ...                          s   
8            c         n          p   ...                          s   
9            c         b          g   ...                          s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [6]:
print(df.shape)

(8124, 23)


#The data available is categorical data and not numerical data. One way to go ahead is map the categories to a corresponding number

# Encoding Categorical data into Numerical Data

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [9]:
le = LabelEncoder()

## apply transformation on each coloumn
ds = df.apply(le.fit_transform)

In [15]:
print(type(ds))

<class 'pandas.core.frame.DataFrame'>


In [16]:
ds.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color   ...     stalk_surface_below_ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [18]:
data = ds.values
print(type(data))
print(data.shape)
print(data[:7,:])

<class 'numpy.ndarray'>
(8124, 23)
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]
 [0 5 3 9 1 0 1 0 0 5 0 2 2 2 7 7 0 2 1 4 2 2 1]
 [0 0 2 8 1 0 1 0 0 2 0 2 2 2 7 7 0 2 1 4 2 2 3]]


# Break the data into training and testing

In [19]:
xtrain , xtest , ytrain , ytest = train_test_split?

In [20]:
dataX = data[:,1:]
dataY = data[:,0]
xtrain , xtest , ytrain , ytest = train_test_split(dataX , dataY , test_size=0.2)

In [21]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(6499, 22)
(1625, 22)
(6499,)
(1625,)


In [23]:
np.unique(ytrain , return_counts=True)

(array([0, 1]), array([3371, 3128]))

## Building our Naive Bayes Classifier

In [27]:
#try
a = np.array([0,0,1,1,0,1,0,1,0,0,1,0,0,0,1])
print(a==1)

print(sum(a==1))
print(sum(a==0))


[False False  True  True False  True False  True False False  True False
 False False  True]
6
9


In [30]:
def priorProb(ytrain , label):
    
    totalEx = ytrain.shape[0]
    classEx = np.sum(ytrain==label)
    
    return (classEx/totalEx)


def cond_prob(xtrain , ytrain , featureCol , featureVal , label):
    
    
    mylabel_x = xtrain[ytrain == label]
    numerator = np.sum(mylabel_x[:,featureCol]==featureVal)
    denominator = mylabel_x.shape[0]
    
    return numerator/float(denominator)

## Computing Posterior probability for each test example and make predictions.


def predict(xtrain , ytrain , xtest):
    # xtest : a single testing point , n features.
    
    classes = np.unique(ytrain)
    numOfFeatures = xtrain.shape[1]
    postProbs = []
    
    for label in classes:
        
        prior = priorProb(ytrain , label)
        likelihood = 1
        for f in range(numOfFeatures):
            likelihood*=cond_prob(xtrain,ytrain,f,xtest[f],label)
    
        
        postProbs.append(prior*likelihood)
        
    pred = np.argmax(postProbs)
    return pred 
    
    
    
def accuracyScore(xtrain , ytrain , xtest , ytest):
    
    ypred=[]
    
    for i in range(xtest.shape[0]):
        predLabel = predict(xtrain , ytrain , xtest[i])
        ypred.append(predLabel)
        
    accuracy = np.sum(ytest==ypred)/ytest.shape[0]
    return accuracy

    

    
    
    
    

In [31]:
print(accuracyScore(xtrain , ytrain , xtest , ytest))

0.9975384615384615
